[package]
name = "disp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2.0"
bincode = "1.3.3"
bytes = "1.1.0"
emulator_6502 = "1.1.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
logos = "0.12.1"
multihash = "0.16.2"
serde = { version = "1.0.139", features = ["derive"] }
thiserror = "1.0.31"

hashdb = { path = "hashdb/" }
anyhow = "1.0.58"
rustyline = "9.1.2"
bytecheck = "0.6.8"
rkyv = { version = "0.7", features = ["validation"] }
typed-arena = "2.0.1"
derivative = "2.2.0"
moveit = "0.5.0"
nom_locate = "4.0.0"
either = "1.7.0"
chumsky = "0.8.0"
smallvec = "1.9.0"
ariadne = "0.1.5"

[features]

[workspace]
members = [
	# "examples/test6502",
]


[workspace.metadata.nix]
nativeBuildInputs = [
	"cargo-edit", "rust-analyzer"
]
buildInputs = []
toolchain = "nightly"
devshell = {name = "rust-dev-shell" }

[package.metadata.nix]
longDescription = """
disp is an in-development built on top of the calculus of inductive constructions and can compile to to assembly.
"""
app = true
build = true
