[package]
name = "disp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2.0"
emulator_6502 = "1.1.0"
hashdb = { path = "../hashdb" }
multihash = "0.15.0"

[features]

[workspace]
members = [
	"examples/test6502",
]
