[package]
name = "disp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2.0"
bincode = "1.3.3"
bytes = "1.1.0"
emulator_6502 = "1.1.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
logos = "0.12.0"
multihash = "0.16.1"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"

hashdb = { path = "hashdb/" }
anyhow = "1.0.53"
rustyline = "9.1.2"
bytecheck = "0.6.7"
rkyv = { version = "0.7.31", features = ["validation"] }
typed-arena = "2.0.1"
derivative = "2.2.0"
moveit = "0.4.0"

[features]

[workspace]
members = [
	"examples/test6502",
]


[workspace.metadata.nix]
nativeBuildInputs = [
	"cargo-edit",
]
buildInputs = []
toolchain = "nightly"
devshell = {name = "rust-dev-shell" }

[package.metadata.nix]
longDescription = """
disp is an in-development built on top of the calculus of inductive constructions and can compile to to assembly.
"""
app = true
build = true
