[package]
name = "hashdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2.0"
digest = "0.10.1"
multihash = "0.15.0"
serde = { version = "1.0.133", features = ["derive"] }
sha3 = "0.10.0"
unsigned-varint = "0.7.1"

[features]
