#set document(title: "The Nature of Abstraction")
#set page(numbering: "1", margin: (x: 2.2cm, y: 2.4cm))
#set heading(numbering: "1.1")
#set par(justify: true)
#set text(size: 10.5pt)

#align(center)[
  #text(size: 19pt, weight: "bold")[The Nature of Abstraction]

  #v(4pt)
  #text(size: 12pt)[What an abstraction is, and whether a language can optimize its own]

  #v(2pt)
  #text(size: 9pt, style: "italic")[Synthesis of a four-way literature and design review for the disp project — 2026-08-14]
]

#v(12pt)

= Introduction: the question, stated so it can be answered

disp is built on tree calculus: one atom, five rewrite rules, with case analysis over arbitrary programs (triage) as a rewrite rule rather than library code \[54\]. Types are ordinary functions from raw trees to verdicts; the trusted core is two Sigma-ops (`bind_hyp`, `hyp_reduce`) plus a dispatcher, about 232 lines. Names in the standard library are owned by guards that demand relation-object evidence for any rebinding, re-verified in-language at every load. The stated endgame is an external optimizer that takes a scoring function — the type checker rendered as 0/1, combined with measured cost — and returns a term maximally satisfying it, eventually improving its own scoring functions by self-play.

Against that background, "should disp actively optimize its own standard library, and by what criterion?" decomposes into four questions:

+ *Should it optimize at all* — is library quality a real, improvable quantity, or taste?
+ *What is the objective* — is there anything more principled than running search on a metric somebody made up?
+ *Do e-graphs fit* — is equality saturation the right substrate in a calculus whose evaluator can branch on syntax?
+ *Does self-application compound* — does an optimizer that improves the library it is written against actually get better, and where does that loop hit a wall?

This document synthesizes four bodies of evidence — the philosophy of abstraction, the mathematics of abstraction (algorithmic information theory, proof complexity, succinctness, category theory), the systems literature (library learning, equality saturation, RL state abstraction, self-improving agents), and a close reading of disp's own machinery — into one argument. The argument, compressed:

*What an abstraction is* has a convergent answer across all four literatures: an equivalence relation over prior objects, together with a representative that clients may swap for any other member of the class. Frege's abstraction principles \[4\], Berkeley's representative particulars \[2\], Benacerraf's interchangeable occupants of structural roles \[13\], the model half of a Kolmogorov two-part code \[16\], a cut formula in a proof \[24\], a Galois-connected abstract domain \[41\], an MDP homomorphism \[66\], and an e-class with an extracted representative \[47\] are the same object wearing eight costumes. disp's relation objects — plain data `{left, right, rel}` with licensing guards — are a ninth costume, and unusually, one that carries machine-checked evidence.

*What makes an abstraction good* has exactly one non-instrumental candidate criterion in the entire surveyed literature: possession of a universal property — being the initial or terminal solution to a well-posed extension problem, unique up to unique isomorphism \[9, 10, 11\]. Everything else — compression, search-cost reduction, invariance, transfer — is relative to a task distribution, and provably so: task-free representation quality is mathematically underdetermined \[59\], transfer guarantees exist only within an explicit task environment \[72, 73\], and even the universal-property criterion relocates rather than eliminates choice (universality is relative to an ambient category, which is itself a level-of-abstraction choice \[8\]).

*What optimizing the library is worth* has a proven scale: a library entry with its predicate-type is a cut, and cut-elimination blows proofs up by a tower of exponentials \[24, 25, 26\]. The stakes are feasibility-class, not constant-factor.

*How to do it soundly* has a precedent: the RL state-abstraction literature, which never asks "is this abstraction good?" before asking "which theorems survive it?" \[65, 66, 67, 68\] — a soundness lattice that maps directly onto disp's existing hierarchy of relation strengths.

The design chapters (Sections 5–8) answer the four questions for disp specifically, incorporating the corrections and surviving objections of an adversarial critique pass: three serious attacks (a conflation between rebinding existing names and introducing new abstractions; a falsified congruence certificate; a ground-versus-schematic gap in the licensed rewrite theory) are folded in as explicit design amendments, and several citation-level errors found by the audit are corrected in place.

= What could a principled criterion even be? (Philosophy)

== Omission versus representative use

The classical account — Locke's — says abstraction is deletion: the mind forms general ideas by leaving out particularizing detail so one idea can apply across individuals \[1\]. This is the ancestor of every information-theoretic quality metric: compression, minimal interfaces, minimum description length. Berkeley's rebuttal is that no deleted-content idea is coherent (there is no idea of a triangle that is every kind of triangle and none); instead a fully particular idea is _used_ to stand for all of a kind — generality is a functional role, not an intrinsic property of any content \[2\].

Berkeley wins in disp's own terms, and this is load-bearing. In a language where types are predicates over raw trees, there are no abstract entities anywhere: only particular terms, and predicates determining which particulars a given particular can stand in for. "Abstractness" of a library component is the extension of the predicate it satisfies — a fact about use-range, never about the token implementation. This licenses the central optimizer move (swap any representative of the class — exactly e-graph class-representative extraction) and dictates where quality must be measured: on the predicate and its role, never on the token. Deletion-based metrics, if Berkeley is right, measure the wrong object.

== Fregean abstraction and the Bad Company problem

Philosophy's most rigorous formal model of abstraction is the Fregean abstraction principle: introduce new objects as the quotient of old ones by an equivalence. Hume's Principle — the number of $F$ equals the number of $G$ iff $F$ and $G$ are equinumerous — contextually defines the cardinals, and Frege's Theorem shows the Dedekind–Peano axioms are derivable from it in second-order logic \[4\]. One well-chosen abstraction generates all of arithmetic: abstraction quality is real, not taste.

But Basic Law V, syntactically the same shape, yields Russell's paradox, and the resulting demarcation problem — the Bad Company objection — is unsolved: proposed criteria (consistency, conservativeness, stability) each face persistent problems, including principles that are individually acceptable but pairwise inconsistent \[5\]. (An audit note: the fine-grained survey of demarcation criteria is better anchored in the SEP Frege's-Theorem entry \[4\] and the primary Bad Company literature than in the Logicism entry alone; the lesson stands either way.) Two consequences for disp:

- *Goodness is non-local.* Individually fine abstractions can be jointly incoherent, so any per-definition abstraction-quality score is provably the wrong shape. The unit of evaluation must be the whole library — in disp terms, the whole barrel under the full load-time test suite.
- *Conservativeness is a usable negative criterion.* A good abstraction proves nothing new and nothing false about what it abstracts from; it only reorganizes. In a language whose types are runnable predicates, conservativeness over the previous library stage is a verification obligation, not a slogan.

== Abstraction versus idealization: the firewall

Godfrey-Smith draws a sharp line: an _abstraction_ leaves things out while remaining literally true; an _idealization_ treats a system as having features it clearly lacks — it "fictionalizes in the service of simplification" \[6\]. Omission is inevitable in any description; fictionalizing is always optional — but in mathematical contexts pure omission is hard, and tends to collapse into idealization. Cartwright radicalizes the warning: the most abstract, most unifying laws are true of nothing actual; explanatory generality and truth trade off \[7\].

This yields a mechanically checkable design principle for disp. A type-as-predicate that a term actually satisfies is an abstraction in the strict sense: literally true, silent about the rest. A cost model, a loss surrogate, an optimizer's simplifying assumption ("steps are proportional to wall-clock", "memory is flat") is an idealization: useful, false, and it must never migrate into the trusted layer. The standard library contains abstractions only; the optimizer may idealize freely provided every result is re-verified against true predicates. Godfrey-Smith's slippage warning bites on spec authorship: a predicate's silence about resource behavior is an implicit assertion that resources do not matter — an idealization wearing an abstraction's clothes — and no criterion exists for when silence is sound (Section 10).

Cartwright's residue survives as the coverage-versus-strength trade-off: a metric rewarding generality will breed interfaces so abstract that no efficient concrete instance usefully satisfies them. Because disp types are runnable, a library abstraction cannot lie — but it can be uselessly weak.

== No view from nowhere: levels and gradients

Floridi's method of levels of abstraction: every analysis fixes a finite set of typed observables (an LoA); questions are meaningful only relative to one; systems support many LoAs organized in a gradient with explicit relations between levels \[8\]. A runnable predicate literally _is_ an LoA — it fixes which observations of a term matter. The consequence is deflationary: "the best abstraction for X" simpliciter is ill-formed; only "best at this level, for this purpose" is well-posed. The constructive suggestion is to optimize the _gradient_: maintain multiple explicitly-related levels — predicates connected by verified refinement maps ($forall t. P(t) arrow.r Q(r(t))$) — rather than one "best" abstraction per concept. disp's spec/overlay architecture, where consumers pick a face from a barrel, is already gradient-shaped.

== Universal properties: the one non-instrumental criterion

Category theory makes the strongest positive offer in the surveyed philosophy: a definition is _canonical_ when it states a universal property — the object is initial or terminal among all candidates, hence unique up to unique isomorphism, with zero arbitrary choices \[10, 11\]. Mac Lane's slogan "all concepts are Kan extensions" (Categories for the Working Mathematician, section X.7 \[9\]; the slogan and the sentence "The notion of Kan extensions subsumes all the other fundamental concepts of category theory" are confirmed via the Wikipedia article on Kan extensions \[10\], not the nLab page) cashes out as: every fundamental construction — limits, colimits, adjoints — is the initial or terminal solution to a functor-extension problem. This is the only answer anywhere in the material to "what makes an abstraction good, _beyond_ serving a purpose": being _the_ answer to a well-posed question rather than _an_ answer.

Concretely for disp, universality is a predicate schema:

```
isProduct(P, fst, snd) :=
  forall X f g. exists-unique h. fst . h == f  and  snd . h == g
```

so "canonical" becomes a checkable library property — with three honest caveats that structure everything downstream:

+ The $exists!$ quantifies over all objects of the ambient category. Such predicates are theorems to verify (proof-carrying side-conditions via `param_apply`), not tests to run — or they must be checked against an enumerable ambient category, with the consequences Section 6 discusses.
+ Universality is relative to the ambient category. Choosing which morphisms count is a prior, purpose-laden choice — Floridi's LoA-relativity resurfaces one level up. Canonicity relocates arbitrariness; it does not eliminate it.
+ Coverage is partial. Many practically vital abstractions (hash maps, schedulers, caches) have no known universal characterization. Where the criterion applies, it converts optimization from "maximize a score" to "exhibit initiality" — a proof obligation, disp's native currency. Where it does not, instrumental criteria are all there is.

Awodey's schematic reading of mathematics — a theorem is about any structure whatever satisfying its hypotheses, with no fixed ontology underneath, and no "one true topos" \[12\] — adds the anti-foundationalist corollary: do not seek a privileged base library everything reduces to. Library entries should be schematic (in any context where these hypotheses hold, this construction exists), which is what makes them portable across the representations an optimizer might later prefer. And Benacerraf's underdetermination — numbers cannot be any particular sets, since many reductions serve equally; identity attaches to the role \[13\] — is the compiler-optimization insight stated in 1965. A library of predicates-as-roles is eliminative structuralism made executable, and it licenses aggressive representation swapping _provided_ downstream code touches entries only through their predicates — i.e., abstraction quality includes an enforcement component, which is checkable.

One gap in the philosophy is disp's to fill: every philosophical account of abstraction is isomorphism-invariant, but cost is not. Two extensionally equal terms differ in steps. disp needs a two-sorted account — structural role (predicate, swap-invariant) plus resource profile (not swap-invariant, the thing optimization improves) — and there is no developed philosophy of resource-sensitive abstraction to import.

== Pragmatism: the bootstrapping license, without a convergence proof

Peirce, James, and Dewey ground the honest default — abstractions are instruments justified by their working — but contribute two things beyond the platitude \[14\]. James's coherence constraint upgrades usefulness from a scalar to a systemic notion (an abstraction's value includes how it composes with everything else — converging with Bad Company from the opposite pole). And Peircean self-correcting inquiry is the direct precedent for disp's bootstrap: the norms and tools of inquiry are themselves products of inquiry, improved by the process they enable, with fallibilism replacing foundations. The regress is not vicious. But pragmatism asserts no convergence, no monotonicity, no fixed point — and cannot rule out self-reinforcing degenerate libraries that satisfy the metric while drifting from the purpose: the philosophical form of reward hacking. What discipline pragmatism lacks, disp can add: each self-improvement step carries a proof of conservativeness over the previous stage's verified predicates.

= The mathematics of abstraction

== The two-part code: "library + programs-given-library" is the canonical decomposition

Kolmogorov complexity admits a two-part form: describe a model $S$ containing $x$, then describe $x$ within $S$. Kolmogorov's structure function

$ h_x (alpha) = min { log |S| : x in S, K(S) lt.eq alpha } $

captures, for an individual object, the full trade-off between model (library) size and residual description length. Vereshchagin and Vitányi prove the MDL estimator implicit in this function finds the best-fitting model at every complexity level with certainty, and that every monotone trade-off curve is realized by some data — there is no universal shape \[16\]. The point where $h_x (alpha)$ meets the sufficiency line $K(x) - alpha$ defines the algorithmic minimal sufficient statistic: the smallest model capturing all regularity, leaving only incompressible noise.

Read onto disp: the library is the model $S$; user programs are the data-to-model code. Two consequences. First, an optimal library for a corpus _exists and is well-defined_ — "optimize the stdlib" is a mathematically coherent goal, not a category error. Second, the optimum is incomputable, and the curve's shape is data-dependent — so any fixed compression metric is an approximation whose divergence from truth cannot itself be computed. The honest epistemic status of any library optimizer is monotone certified improvement toward an unknowable optimum: a found two-part code is a certified upper bound; optimality and distance-to-optimality are never certifiable.

Gács, Tromp, and Vitányi supply the failure modes \[17\]: without a constraint separating model from data parts, naive minimization admits degenerate models — $S = {x}$ (one bespoke combinator per program: overfit) and $S$ = everything (empty library: underfit) — that are formally optimal and meaningless. Any disp metric must penalize library complexity and program complexity on the same scale, and the theory says the boundary between them is a real per-corpus quantity, not a convention. There also exist non-stochastic objects with _no_ small sufficient statistic at all. MDL proper \[18, 19\] is the computable projection: restrict to a model class, minimize codelength of model plus codelength of data given model; refined MDL (normalized maximum likelihood) removes the residual arbitrariness of how the model part is encoded — a concrete upgrade over DreamCoder-style two-part scoring. The objective should be a genuine prefix-free codelength over tree-calculus terms, including the cost of naming and typing library entries — not token counts.

== Sophistication and logical depth: structure worth keeping is not compressibility

$K(x)$ cannot distinguish random from structured — random strings maximize it. Sophistication (the length of the function part of a near-minimal two-part description \[20\]) and Bennett's logical depth (the running time of near-minimal programs producing $x$ \[22\]) both formalize "meaningful structure", and both are less computable than $K$ itself. Two verified results matter for metric design:

- *Instability.* Antunes and Fortnow show sophistication is severely unstable: changing the allowed slack by $O(log n)$ can collapse a string's sophistication from nearly $n$ to nearly $0$; their smoothed "coarse sophistication" coincides (up to log factors) with computational depth \[21\]. Engineering translation: a stdlib optimizer hill-climbing a sharp threshold objective will thrash under tiny corpus changes. Use smoothed, slack-penalized objectives; expose the tolerance knob rather than hiding it.
- *The depth threshold.* Ay, Müller, and Szkoła prove that if effective complexity (description length of an object's regularities) exceeds a threshold, logical depth is astronomically large \[23\]. Prediction: past a certain richness of the library, further genuine improvements require super-polynomially growing search — which argues for anytime, budgeted optimizers rather than metrics assumed cheap to optimize.

Bennett's reading (title, venue, and the definition verified; the finer details from model memory \[22\]) is the deepest conceptual match to "is this abstraction worth keeping": a good library entry is _cached depth_ — expensive-to-rediscover, cheap-to-reuse computational work — and the slow-growth law (fast processes cannot create depth) formalizes why library discovery must be expensive. You cannot cheaply generate genuinely valuable abstractions, only cheaply reuse them.

== Cut is abstraction, and abstraction is non-elementary compression

In proof theory a lemma is a cut, and a cut is an abstraction. Boolos exhibits a concrete first-order inference with a one-page derivation using cut whose cut-free derivation is too large to physically write \[24\]. Orevkov and Statman upgrade the example to a theorem schema: there are sequences of theorems with proofs of length $n$ using cuts whose shortest cut-free proofs have length $2_n$, the tower of exponentials ($2_0 = 1$, $2_(n+1) = 2^(2_n)$) \[25, 26\] — both results verified via the reference list and introduction of Hetzl et al. \[27\], which states the bound verbatim. Since disp programs carry proofs — types are predicates, checked at load — stdlib entries are cuts, and the stakes of library optimization are tower-of-exponentials stakes in term and proof size. This is the strongest formal warrant for library optimization in all of the surveyed mathematics: refusing to optimize the lemma library can cost you the universe.

The constructive direction — _cut-introduction_, computing lemmas rather than eliminating them — is the proof-theoretic blueprint for principled library learning. Hetzl, Leitsch, Reis, and Weller invert Gentzen \[27\]: given a cut-free proof, extract its Herbrand disjunction (a finite term language); find a small tree grammar generating that language (pure compression, metric-driven); then _solve_ — by unification, not search — for a $Pi_1$ cut formula whose introduction realizes the grammar's compression. The separation is the design lesson: the combinatorial question (find a small grammatical cover of the corpus) is distinct from the logical question (does a lemma realizing this cover _exist_). The program's honest stall points, documented in the follow-up work \[28\]: minimal-grammar search is a hard combinatorial optimization; lemma shapes are restricted (mostly $Pi_1$, few quantifier alternations); and — critically — the _realizability gap_: many compressive grammars admit no realizing cut formula at all, so corpus-level compression overpromises logic-level compression. Eberhard and Hetzl close the negative side: proof compressibility by cuts is formally equivalent to tree-grammar compressibility of finite languages, and there are proof sequences no cut-introduction method can compress \[29\]. A plateau can be a property of the corpus, not a bug in the optimizer — and, pleasingly for a _tree_ calculus, tree-grammar induction is thereby the mathematically canonical library-learning algorithm for disp's substrate.

disp's structural advantage over the sequent-calculus setting: realizability is an executable check. A candidate abstraction either admits a synthesized relation-object contract whose license proof discharges, or it does not — attempt the proof, discard on failure. Whether tree-calculus reflection _enlarges_ the class of realizable lemmas is open.

== Succinctness, not expressiveness, is the design axis

Tree calculus is Turing-complete, so every possible stdlib is "equally expressive" and expressiveness arguments are vacuous. The real axis is succinctness: formalisms of identical expressive power differing in description size. The corrected statement of the key results (the original sweep misstated them, and the audit's correction is applied here): Grohe and Schweikardt show that on linear orders the 2-variable and 3-variable fragments of first-order logic have the same succinctness up to a polynomial factor, the 4-variable fragment is _exponentially_ more succinct than the 3-variable fragment, and the _non-elementary_ succinctness gap they prove is between the FO-expressive fragment of monadic second-order logic and FO itself \[30\]. Hella and Vilander give an independent non-elementary example — bisimulation-invariant FO versus modal logic — via a formula-size game \[31\]. So the qualitative point survives correction: equal expressive power hides representation gaps up to non-elementary, and reasoning cost scales with the representation, not the semantics. Library choices determine whether specs are physically writable.

The methodological gift is the game itself: size games are _adversarial certificates_ that one basis is inherently more succinct than another for a class of specifications. A disp-native analogue — a game on tree-calculus terms modulo the type predicates — would let an optimizer _prove_ a library change is an improvement on a spec class, rather than observe it on a finite corpus. Nobody has built this for a programming language.

== Galois connections and parametricity: two definitions, no rankings

Abstract interpretation is the closest thing PL owns to a mathematics of abstraction, and it is adjunction-shaped. Cousot and Cousot: program properties form lattices; an abstraction is a Galois connection $alpha tack.l gamma$ between concrete and abstract lattices; abstract fixpoints soundly approximate concrete ones; and consistent abstract interpretations themselves form a lattice — abstractions are ordered and composable \[41\]. The 1979 sequel adds the punchline: given the connection, there _exists a best abstract transformer_, $alpha compose f compose gamma$ — the unique most-precise sound approximation of concrete $f$ in the chosen domain \[42\]. Relative to a chosen abstraction, optimality of the operations is _defined_, a mathematical object an optimizer can aim at. What the framework does not give: any ranking over abstract domains themselves. "Abstraction quality" splits into reaching the best transformer (solved, definitional) and picking the right lattice (open — abstract-domain synthesis), and it is exactly in the second half that compression-style search sneaks back in.

Parametricity is the other definition-not-metric. Reynolds' abstraction theorem generalizes homomorphisms to relations: any well-typed term maps related environments to related results, so two representations related by any interface-respecting relation are indistinguishable by clients — representation independence \[38\]. (Audit note applied: the canonical thesis sentence is "type structure is a syntactic discipline for _enforcing_ levels of abstraction"; the scanned PDF at the recorded URL has no extractable text layer, so the sweep's verbatim-quote claim is downgraded — title, venue, and content are confirmed via secondary sources.) Wadler operationalizes it: from a polymorphic type alone, derive a theorem every inhabitant satisfies \[39\] — types are cheap theorems about abstraction boundaries, and free theorems are exactly the equational input library-learning-modulo-theory wants.

The critical tension: _parametricity is false in tree calculus by design._ Triage branches on argument syntax, so extensionally-equal implementations are distinguishable by some inspecting context, and free theorems fail. disp's response, already implemented in the kernel, is to police reflection: raw triage on a neutral hypothesis and stem-forging are errors, pinned in the soundness tests. Representation independence is thereby not a metatheorem but a per-boundary, machine-checked property — Liskov and Zilles' enforcement boundary \[40\] rebuilt as a proof obligation. Whether the checkable parametric fragment is large enough to host a useful stdlib is an open problem (Section 10).

== Kan extensions: optimality without a metric — and what it does not buy

The category-theoretic alternative to "search on a metric": pose the extension problem as a functor situation, and the left/right Kan extension _is_ the best approximation from below/above — adjoint to precomposition, computed pointwise by (co)ends, unique up to unique isomorphism, no tunable parameters \[32\]. Shiebler shows these constructions operationalize into actual algorithms: "extend $f$ from a small set to a larger set, optimally" — the core ML generalization problem — is literally a Kan extension, with the left/right choice corresponding to the most-liberal/most-conservative consistent extension \[33\]. For disp, "given behavior on the corpus, what should the abstraction do on unseen inputs" has two canonical answers, and a language with runnable predicates can implement both and check them against the spec.

The honest synthesis, though, is a division of labor. The universal property is only as good as the chosen categories and the functor along which one extends: Kan extensions relocate the design choice from "which metric" to "which interface functor". Universal properties fix what "optimal abstraction" _means_ once an interface is chosen; search — MDL-driven, over e-graphs — chooses the interface. Whether the relevant category of tree-calculus terms modulo observational equivalence has enough (co)limits for pointwise Kan extensions is entirely unexplored.

== Coarse-graining, decidability, and the bottleneck

Two physics-adjacent results complete the picture. Israeli and Goldenfeld construct local coarse-grainings of cellular automata — including computationally _undecidable_ ones — whose large-scale dynamics obey strictly simpler, predictable rules \[35\]: the right abstraction can move questions across the decidability boundary. For a self-verifying language this is the whole game. disp's type predicates are undecidable in general, but a stdlib of the right coarse-grained combinators can make the properties users actually state decidable or cheaply checkable. Abstraction quality is partly a _decidability-engineering_ question, invisible to every size metric, and formalized nowhere. (Mehta and Schwab's exact mapping between variational renormalization and deep-network layers \[34\] supplies the flow picture: abstract, measure induced error against the spec, re-abstract — a flow with error control, not a one-shot optimization.)

The information bottleneck \[36\] is the template for letting the task define the metric: given source $X$ and relevance variable $Y$, minimize $I(X;Z) - beta dot I(Z;Y)$ — the effective distortion measure _emerges_ from what you want to predict, rather than being hand-designed (its ancestor, rate-distortion theory \[37\], required a hand-chosen distortion function). Sweeping $beta$ traces a frontier: there is no single optimal abstraction, there is a curve. disp uniquely possesses the relevance variable already — the spec predicates. But the analogy must be stated at its true strength (the audit's deflation is accepted): IB is defined over joint distributions, a term-level algorithmic IB is unbuilt open territory, and what disp's design actually delivers is not "the metric emerges" but "the corpus _is_ the metric, made explicit and versioned" — which is the honest, Locatello-compliant position (Section 6).

= Systems that learn libraries

== Library learning: DreamCoder, Stitch, babble — the actual objectives

DreamCoder \[50\] is the strongest published argument that a library is not a convenience but _the learned prior that makes future search tractable_. Its wake-sleep loop: wake — solve tasks by neurally-guided program search; sleep-abstraction — compress solved programs into new library primitives under a Bayesian MDL objective (maximize the posterior of the library given the corpus: a prior over libraries proportional to description length, times the description length of solutions rewritten in the library); sleep-dreaming — retrain the neural recognizer on samples from the current library. It rediscovers map, fold, vector algebra, and physics laws, building multi-layer concept towers where each library generation makes previously unreachable tasks reachable. Crucially, compression is _gated by task success_ — an abstraction is accepted only if the posterior improves, i.e., the metric is subordinated to the specs. This is already a weak, non-proof-carrying self-improvement loop, and the empirical case that library optimization compounds.

Stitch \[51\] shows the objective is cheap: corpus-guided top-down search over the space of abstractions themselves (patterns with holes), branch-and-bound pruned by an admissible compression bound — three to four orders of magnitude faster than DreamCoder's refactoring, two orders less memory, equal or better compression, anytime. Library learning can be a normal toolchain phase, not an offline research artifact.

babble \[49\] is the most load-bearing precedent for disp: _library learning modulo a theory_. Its algorithm, verified at PDF level: (1) run equality saturation with a user-supplied equational theory to build an e-graph representing all corpora equivalent to the input; (2) generate candidate abstractions by anti-unification performed directly on e-classes — dominant anti-unifiers, with "generality filters" discarding patterns that are too concrete (match once) or too abstract (everywhere dominated by a more concrete pattern), candidates restricted to most-concrete patterns matching some pair of subterms (an avowedly incomplete heuristic); (3) reduce candidate selection to e-graph extraction — each candidate becomes a rewrite introducing a local lambda-abstraction at match sites, and the best library minimizes the size of the smallest extractable term, solved by an approximate "targeted common subexpression elimination". The objective is total AST size of library plus refactored corpus, computed modulo the theory — orders of magnitude better compression than syntactic library learning, robust to semantics-preserving variation.

What is principled in this lineage: the MDL skeleton (Section 3.1) and babble's quotient-by-semantics move. What is ad hoc: the cost model (raw AST nodes — blind to runtime, proof length, check-time, legibility), the incomplete candidate heuristics, and above all the fact that babble's equational theory is _user-supplied_ — babble discovers no equations. For a reflective language this last weakness inverts into the right interface: in a calculus where programs can inspect syntax, an equational theory is a _choice of which observers to respect_ — a design decision, not a discovery — and disp's relation objects are exactly the artifact in which such a choice is stated with evidence attached. (Section 7 confronts the serious catch: the licenses disp has today are ground facts, and babble needs schematic rules.)

== E-graphs and egglog

egg \[47\] made e-graphs a practical, reusable optimizer substrate: apply all rewrites simultaneously, never destroy information, extract at the end — eliminating phase ordering, the classic failure of "run search on a metric". Its two contributions matter individually to disp: deferred rebuilding (amortized congruence restoration), and e-class analyses — lattice-valued facts attached to e-classes, the hook by which predicate-satisfaction facts and cost provenance can participate in extraction. egglog \[48\] unifies Datalog with equality saturation in one fixpoint system: relations, guarded/conditional rules, congruence, extraction. Its guarded rules are the most plausible mechanism for restricting rewrites to certified contexts — which Section 7 argues is the fix reflection demands. The substrate is converging toward "a database of terms plus a logic over them", something disp could expose as an ordinary library rather than a privileged pass.

== RL state abstraction: the soundness-first precedent

The RL literature is the one place where abstraction arrives with theorems attached, and its shape is the template disp should copy. Ravindran and Barto define MDP homomorphisms — structure-preserving maps on state-action pairs commuting with dynamics and reward — with optimal policies in the quotient lifting to optimal policies in the original \[66\]: abstraction as a commuting square with a proof, the exact analogue of a licensed rewrite. Li, Walsh, and Littman order five abstraction classes by coarseness and prove which guarantees survive at each level — bisimulation preserves everything; the coarsest classes preserve only the optimal policy and can break learning \[65\]: an explicit soundness lattice trading compression against surviving theorems. Ferns, Panangaden, and Precup soften exact bisimulation into metrics via the Kantorovich distance, with $|V^*(s) - V^*(s prime)| lt.eq d(s, s prime)$ \[67\]; Abel, Hershkowitz, and Littman prove value-loss bounds for approximate abstractions — treating $epsilon$-similar states as identical costs a controlled function of $epsilon$ \[68\].

The mapping onto disp is direct. The soundness lattice is disp's relation-strength hierarchy: `tree_eq` (hash-cons identity — bisimulation-grade, preserves everything including inspection) above pointwise-refl-licensed relations, above `PositiveFnCoverage`-discharged structural equivalence, above `Quotient`/`q_lift` coarse observational equality. And the $epsilon$-metric end of the lattice — "these terms are $epsilon$-interchangeable for this loss, with certified regret" — has _no program-optimization analogue anywhere_: e-graphs implement only the exact end. Runnable predicates parameterized by tolerance make the metric end buildable in disp; nobody has built it (Section 10).

== Macro-operators, chunking, production compilation

Korf: a macro-operator's value is the search-graph distance it collapses — macros convert non-serializable subgoal sets into serializable ones, turning exponential searches trivial \[70\]. Abstraction quality as a property of the _search topology_, not the data — and a runnable, non-proxy metric: measure expected optimizer search cost over a benchmark distribution with and without the candidate. Chase and Simon: chess masters reconstruct game positions vastly better than novices but are no better on random boards — expertise is a grown, distribution-specific library of chunks \[69\]. Both halves of disp's question are answered here in 1973: yes, grow the library; and no metric can be task-free, since chunks are valuable only on the distribution that trained them. ACT-R's production compilation \[71\] adds the retention policy: compile only traces that actually recur, keep both the compiled shortcut and the general path, and let measured utility — not a static metric — govern tenure. Trace-driven, reversible library growth.

Voyager \[55\] is the modern uncertified version: an LLM agent with an automatic curriculum proposing tasks at the frontier of ability and an ever-growing skill library of executable code, where later skills call earlier ones and ablating the library collapses performance. Compounding with no formal metric at all — selection is "did the composed program work". The transferable ideas are the auto-curriculum (which answers "which task distribution do we compress for" endogenously) and skill indexing; the missing piece Voyager cannot have and disp uniquely can add is verified interfaces on stored skills.

== mathlib: the social process

The strongest _existing practice_ of actively optimizing a stdlib for abstraction quality is not algorithmic — it is mathlib's distributed social organization \[52\]: maintainer review, linters enforcing conventions, and the norm that when a lemma is found to be a special case, the generalization is adopted and the whole library refactored under you. That norm is manual anti-unification plus a transaction system. The lesson is architectural: abstraction-quality governance needs a fitness function _plus refactoring mechanics_ — cheap, atomic, trustworthy whole-corpus rewrites — and the mechanics, not the fitness function, are the observed bottleneck. mathlib optimizes mathematician-legibility and proof reuse, objectives with no formal definition; the DreamCoder line optimizes a formal objective with no legibility. Nobody has closed that gap, and superoptimizer outputs \[44, 45\] show compression can actively diverge from legibility.

== Superoptimization, staging, and the Gödel machine

Massalin's superoptimizer \[44\] — enumerate instruction sequences shortest-first, filter by test vectors — is the ancestral form of disp's "spec in, maximally-satisfying term out", and its cautionary tale: exhaustive search dies past a dozen instructions, and the outputs are anti-abstractions, incompressible and unreadable. STOKE \[45\] recasts the problem as MCMC over a cost function combining correctness (tests plus verification) and performance — direct evidence that "the predicate is the executable loss term" works, with re-verification after search. Superoptimization specializes single programs; library learning amortizes across a corpus; the unexplored synthesis — the learned library as the proposal distribution for the superoptimizer — is exactly disp's bootstrapping story. MetaML \[46\] is the standing counter-position: keep abstractions maximally general and eliminate their cost per use-site by staging. In tree calculus staging is nearly native (programs are inspectable values, quotation is free), so disp gets the benefit without the type machinery — but staging (unfold) and library learning (fold) are inverse rewrites, and no literature gives a policy for which wins where.

Schmidhuber's Gödel machine \[53\] is the formal ancestor of the endgame: a solver that rewrites any part of its own code as soon as its embedded prover finds a proof that the rewrite increases expected utility, with a Global Optimality Theorem (the proof internalizes the opportunity cost of further proof search, so no local-maxima traps by construction). The double-edged verdict after twenty years: the framework is coherent and wirehead-resistant, and no non-trivial implementation exists, because proof search over self-referential utility statements is intractable. Everitt, Filan, Daswani, and Hutter contribute the one sharp safety theorem in the area \[74\]: self-modification preserves goal content iff the agent evaluates candidate modifications with the _current_ utility function applied to the anticipated post-modification future; agents that evaluate with the modified utility can self-corrupt. Section 8 maps both onto disp — carefully, since the mapping is partly analogy.

= Design I. Should disp optimize its own library?

*Position: yes — as a licensed overlay economy on narrow slices now, deferring whole-library refactoring until the spec corpus is a meaningful task distribution.* Three independent lines converge, and disp has partially pre-paid the cost that usually makes the enterprise risky.

+ *Feasibility-class stakes.* A stdlib entry with its predicate-type is a cut; cut-elimination is non-elementary \[24, 25, 26\]. In a language where programs carry proofs, the lemma library is worth towers of exponentials. Succinctness theory adds that in a Turing-complete substrate, representation size at equal power is the whole design axis, with gaps ranging up to non-elementary — anchored, per the audit's correction, on the MSO-fragment-versus-FO and modal-versus-FO results \[30, 31\], not the finite-variable hierarchy (which is exponential).
+ *The library is the optimizer's prior.* Korf's traversal metric \[70\], Chase and Simon's chunks \[69\], and DreamCoder's concept towers \[50\] agree: since disp's endgame is an external combinatorial-search optimizer, stdlib quality is not hygiene — it is the optimizer's asymptotic search budget.
+ *The transaction mechanics exist — for half the problem.* mathlib says the bottleneck is cheap, atomic, trustworthy whole-library rewrites \[52\]. disp has mechanized exactly that for _rebinding existing guard-owned names_: `license_guard`/`two_face_guard` rebinds re-verified in-language at every load, driver-stamped certs, splice reconciliation, deployment as one `open` line in a barrel, reversible by removing it, with the spec face never edited.

*The critique's serious caveat, adopted.* The feasibility premise as originally argued overstated itself by conflating two activities. The mechanized machinery covers rebinding _existing_ names. Library learning proper discovers _new_ abstractions by anti-unification — and a new abstraction has no incumbent guard-owned name to rebind, so it cannot deploy "in exactly the `nat.opt.disp` shape": that shape is defined by an incumbent relation object owning a name. Worse, the MDL gain of a new abstraction is realized only by refactoring corpus programs to call it — which edits exactly the spec and test faces the argument claimed were structurally insulated from churn. So the mathlib transaction problem is _not_ already paid for; only the face-swap half is. Two consequences: the design must include a declared pathway for introducing new guarded names (a spec-module addition carrying a synthesized relation contract, subject to review) and a corpus-refactoring transaction story; and until those exist, measured MDL gains from novel abstractions are _hypothetical_ (computable, reportable, not deployable). The timing conclusion — narrow slices now — survives and is in fact strengthened.

*The counter-case constrains the form, not the verdict.* (a) Incomputability and instability: the true objective is incomputable \[16\], provably unstable under $O(log n)$ slack changes \[21\], and some corpora are grammatically incompressible \[29\] — so claim monotone certified improvement, never optimality, use smoothed objectives with hysteresis, and treat plateaus as possibly real. (b) Goodhart: the most celebrated "compression causes generalization" claim in ML — the information-plane story \[56\] — collapsed under measurement scrutiny \[57\]: the compression phase was an artifact of saturating nonlinearities, and networks that never compress still generalize. A compression metric can improve while the property you cared about does not; tie metrics to actual downstream solve-cost. (c) Corpus poverty: disp's current corpus (roughly 3,500 library lines, roughly 1,200 test pins skewed toward soundness pins) is a thin relevance variable. Task-free quality is mathematically underdetermined \[59\]; transfer guarantees exist only within a task distribution \[72\]; and undiverse task sets provably yield structure that fails to transfer \[73\]. Globally refactoring against today's corpus would overfit it — which is why growing and diversifying the spec corpus is itself on the critical path.

Evaluation is joint, never per-entry — the Bad Company lesson \[5\]: individually fine abstractions can be jointly incoherent, so the unit of evaluation is the overlay set (the barrel) under whole-suite load-time obligations.

= Design II. The objective: a layered gate–frontier–tier structure

The recommendation is a layered objective in which the only hard "metric" is admissibility, not score.

*Layer 0 — the gate (soundness first).* A candidate abstraction or rewrite is admissible only if it carries a machine-checked license: a `{new; proof}` payload against the name's stated relation object, re-verified at every load (`license_guard`, `two_face_guard`, with `PositiveFnCoverage` per-constructor obligations for concrete faces). Nothing unlicensed is ever ranked. This is the RL soundness-lattice framing \[65\] imported wholesale, and disp already owns the mechanism. The gate converts the objective from "define goodness" — which Sections 2–3 argue is not fully definable — to "rank within the licensed set", which is.

*Layer 1 — the frontier, never a scalar.* Among licensed candidates, maintain a Pareto frontier over two measured axes: (a) two-part MDL of the corpus, computed modulo the licensed rewrite theory — the babble move \[49\], with the theory parameter instantiated by disp's own relation objects; and (b) measured cost, `ApplyStats.steps` over the versioned spec corpus — Korf's traversal metric made runnable \[70\]. Do not scalarize: the IB $beta$-sweep \[36\] and the bisimulation-metric line \[67, 68\] both say the object is a frontier; step counts are backend-declared and incomparable across backends, so a scalar mixing them is meaningless; and disp's barrel mechanism is already deployment-side frontier selection — consumers pick a face.

Two amendments from the critique are folded into this layer. First, the _ground-versus-schematic gap_ (serious): babble's theory consists of schematic rewrite rules with pattern variables — that is what makes saturation grow e-graphs and lets anti-unification find semantically shared structure. disp's licenses today are ground facts: `R old new` relates two specific closed implementations of one name. A vocabulary of a handful of ground equations quotients almost nothing; the e-graph modulo them is nearly the syntactic e-graph, and axis (a) collapses toward Stitch-grade syntactic MDL. Until disp licenses _quantified_ rewrite-rule families (`rel_pi`/`pointwise`-shaped, applicable at any matching site — a different licensing object than name-rebind guards, and one that must be designed and costed), the "modulo licensed relations" axis must be reported honestly as "modulo the small licensed vocabulary", with the opt_q1 map-fusion slice as the only schematic seed. Second, the _MDL realizability discount_: per Hetzl's gap \[27, 28\], compressive candidates that admit no licensable contract are not abstractions; the pipeline discards them at the gate, and disp's advantage is that the discard test is executable.

*Layer 2 — the canonicity tier, revocable.* Where an entry admits a universal-property characterization, verify it as a proof-carrying side-condition and rank such entries above metric-only ones — canonicity as tier, not score, reflecting that the criterion is real but partial \[9, 10, 11\]. The critique's correction is adopted: universality checked against the currently-enumerated library objects is not initiality in any stable sense — the check is non-monotone, since the next library addition can produce a competitor with no mediating morphism. The tier is therefore stamped *canonical-in-barrel-vN*: a per-barrel, revocable status recomputed at every barrel promotion, never a permanent rank — precisely the Bad Company non-locality, resurfacing where the design's own reasoning predicts it. Law packages (functor, monoid, recursor laws) hang on `MetaShape.behavioral_specs` as relation-object bundles — Higgins-style law-alignment \[60\] as a checkable bias term.

*Layer 3 — the corpus is the metric, explicitly.* The relevance variable — the spec corpus — is a first-class, versioned, diversity-audited artifact. The original design framed this as the IB move ("the metric emerges from the specs, dissolving the who-chose-the-metric objection"); the critique's deflation is accepted: the choice does not dissolve, it _moves_ — into the corpus and the relation objects. What is actually delivered is that the only designed objects are reviewable disp artifacts rather than constants buried in an optimizer, which is the honest, Locatello-compliant \[59\] and Baxter-compliant \[72\] position: the corpus is the definition of library quality, so it must be visible, versioned, and audited for the diversity that transfer theory attaches a theorem to \[73\].

One axis is logged as research rather than faked as a number: Felleisen-style locality \[43\] — an abstraction's value as the non-locality client code suffers without it — captures what compression misses (entanglement, not frequency), but is defined for language constructs, and inlining trivializes it for library terms. A formal "locality of elimination" for libraries does not exist.

= Design III. E-graphs under reflection

== The problem

Standard equality saturation assumes every rewrite is a congruence in every context \[47\]. In tree calculus that assumption is false _by design_: triage is a rewrite rule that branches on argument syntax, so behaviorally-equal-but-tree-distinct terms are distinguishable by some inspecting context, and merging them into one e-class licenses extractions that change observable behavior. Neither literature sweep found published work handling e-graphs over an intensional, reflective calculus — but per the critique, this negative-existence claim rests on this project's own searches: adjacent lines (slotted and binder-aware e-graphs, egglog's guarded rules and conditional congruence, context-sensitive e-graph variants) were not audited, and the gap should be treated as a flagged search result to be surveyed before staking a publication claim on it, not as established fact.

The fix in one sentence: stop building e-graphs modulo "equality" and build them modulo _licensed relations_ — which is exactly the ontology the philosophy independently derived (an abstraction is an equivalence class with an extracted representative \[2, 4, 13\]) and exactly the artifact disp's relation objects implement.

== When is congruence sound? (Corrected analysis)

Merging $a$ and $b$ in a class keyed by relation object $R$ is sound iff there is a checked witness of $R space a space b$, _and_ the congruence rule — from $R space a space b$ infer relatedness of $f(a)$ and $f(b)$ — is applied only through contexts $f$ that provably respect $R$. disp's `respects` combinator is literally this side-condition as a first-class object. Three regimes:

- *Finest, free:* `tree_eq` (hash-cons identity) is a congruence for all contexts, inspecting ones included. The existing hash-consed store already is this e-graph layer.
- *Licensed:* for $R$ coarser than `tree_eq`, congruence holds only for non-inspecting contexts, and each context needs a certificate.
- *Coarsest:* `Quotient`/`q_lift` — consumers checked against a `{map, resp}` morphism pair are congruent by construction, the lane for rewrites visible only up to coarse observational equality.

The original analysis proposed a cheap certificate for the middle regime: "any context that typechecks against a Pi over abstract arguments is non-inspecting on those arguments, so passing `param_apply` at the relevant Pi-type certifies respect." *The critique falsifies this, with a counterexample supplied by disp's own machinery, and the correction is adopted in full.* `param_apply` probes behavior only on a _neutral hypothesis_; the kernel guards (triage-on-neutral errors, stem-forge errors) prevent inspection of the hypothesis — not of concrete arguments. A term can branch on `is_neutral` — `two_face` itself is literally the term that delegates on the neutral face and runs new code otherwise, and it typechecks — and then triage concrete arguments freely, or exploit the `tree_eq` two-stage reader carve-out. Such a context passes Pi-checking yet distinguishes $R$-related concrete terms for any $R$ coarser than `tree_eq`. Congruence gated on that certificate can merge unsoundly.

The repaired gate: congruence closure over the licensed layer is gated on _discharged `respects` proof obligations_ — actual relation-object evidence that the context maps $R$-related inputs to $R prime$-related outputs — with `PositiveFnCoverage` as the discharge template where the context's argument type has a positive code, and `s_comp_rel` composition for chains. Pi-typechecking certifies nothing about concrete-face inspection; it never enters the trust story. Contexts that legitimately inspect (recognizers, `is_neutral`-guarded optimized bodies) treat e-class members as distinct — a *two-sorted e-graph*: code-as-data positions admit only `tree_eq`; code-in-application positions admit $R$ where a respects-certificate exists.

The `two_face` constraint threads through cleanly and defines the honest lane: extraction on the checking path must be tree-identical to the spec (the neutral face delegates verbatim), so the e-graph optimizes the _concrete face only_ — which is what keeps pointwise-refl license proofs valid and downstream Pi-checking and inductive conversions unchanged.

== The proposal

Build the e-graph engine _external and certificate-producing, never trusted_: an egglog-style engine \[48\] over `rust-ic-net` (the designated optimizer substrate — materialized interaction net, per-candidate cost provenance, structurally incapable of being a checker backend, which cleanly separates search substrate from trusted checking). Merges require relation witnesses — starting vocabulary: exactly the rewrites already licensed (`nat.opt`, `case.opt`, the opt_q1 map-fusion slice), with the schematic-rule licensing pathway of Section 6 as the growth direction. Congruence closure is gated by discharged `respects` obligations encoded as egglog guarded rules. E-class analyses carry predicate-satisfaction facts and step provenance. Extraction emits `(e', cert)` overlay files for incumbent names — and, for genuinely new abstractions, spec-module addition proposals carrying synthesized relation contracts, routed through the new-name pathway of Section 5 rather than pretending to be rebinds. The entire trust story remains "the kernel re-verifies the license at load": zero kernel changes, matching the established bar. Defense in depth is real: because every emitted overlay is re-licensed in-language at load and pinned differentially, a congruence leak in the untrusted engine degrades to a load failure or a differential-pin failure, not silent unsoundness.

babble's anti-unification transfers with two amendments: the theory parameter is instantiated by the library's own stated contracts (`NatRecRelation`, `AddRelation`, `case_value`'s relation — the names that "state their optimizer contracts directly"), and every anti-unifier must pass the realizability gate — a candidate is a library entry only when a relation-object contract can be synthesized for it and its license proof discharged, the step no published library learner has \[27, 49\].

= Design IV. Self-application: what compounds, what walls

*The optimizer benefits from optimizing the library — through one specific, evidenced channel.* The Gödel machine \[53\] proves proof-carrying self-modification coherent; twenty years of non-implementation prove the bottleneck is proof-search cost. disp's licenses are the Gödel machine's substrate in miniature — `{new; proof}` re-verified at every load is a running proof-carrying modification protocol — but disp should not attempt the global move (proving whole-self rewrites optimal). The evidenced loop is DreamCoder's: _the library is the optimizer's prior_ \[50\], and the optimizer is a client of the stdlib.

What compounds:

+ *Optimizer-as-library-client.* Licensed improvements to the recursors, folds, and functor maps that both the checker's library and the optimizer's own scoring functions are built from make the optimizer's evaluation, checking, and candidate terms cheaper — no self-rewrite occurs, yet the optimizer improves, with the improvement machine-checked by machinery it does not control. Caveat from the critique, adopted: the specific claim that one licensed rebind in the generic-operations module optimizes every inductive at once presupposes the generic recursors are guard-owned with stated relation objects, which is not currently documented; if they are not, that channel requires uncosted setup work (stating the contracts and taking ownership) before it pays.
+ *The search prior.* A compressed library shortens candidate terms, shrinking the combinatorial space per task — Korf's topology change \[70\]; Voyager shows even uncertified skill libraries compound this way \[55\]; disp adds certificates.
+ *Proof discharge.* As relation combinators, coverage templates, and composition lemmas accumulate, license proofs for new rewrites get shorter and more mechanical — the plausible analogue of the Gödel machine's missing inner loop. This rests on the _compression-shortens-proofs conjecture_, which is unproven: DreamCoder demonstrates that compression aids search, not that it shortens proofs, and the connection to proof-theoretic speed-up phenomena remains a from-memory lead, flagged as such.
+ *Self-play scoring.* Score functions are ordinary library values, so an improved library yields cheaper, richer score functions and better curricula — Voyager's auto-curriculum with proofs attached.

What walls:

+ *The Löbian wall.* A system cannot prove its own proof-acceptance sound, so the trusted core (`bind_hyp`, `hyp_reduce`, `param_apply`) _and the license-checking machinery itself_ (the relation and guard library, the declaration protocol) stay outside the optimization loop. Freeze them — the `freeze` guard exists — and treat any change there as an external, human-reviewed event. The precise failure to police is optimization pressure drifting into the relation library ("improve the relation objects for better scores"): changing the license checker is changing what counts as a proof.
+ *The neutral-face wall.* `two_face` keeps the spec on the checking path, so checking-time cost of guarded names never improves through the licensed lane — only concrete-face runtime does. An entire axis of self-speedup is structurally unreachable without solving observer-restricted certification, which is the project's stated open problem. This stagnation is by design; the one "fix" that would break the system is weakening observer restrictions for throughput.
+ *No acceleration theorem.* Compounding is empirical (DreamCoder, Voyager), never proven; plateaus are mathematically real (corpus incompressibility \[29\]; the depth threshold \[23\]). The honest expectation is a ratchet with diminishing returns, not takeoff.
+ *Generational convergence.* Wentworth's convergence claim — diverse optimizers learn the same abstractions — has no selection theorem \[62, 63, 64\]; nothing guarantees generation $n+1$'s library remains intelligible to generation $n$'s contracts beyond what the licenses enforce. Which is exactly why licenses are never weakened.

On safety: Everitt et al.'s theorem \[74\] — evaluate candidate self-modifications with the _current_ utility over the post-modification future — is the right principle, and disp's guard ownership genuinely delivers its conclusion: the incumbent relation object owns the name, the new face must satisfy the _old_ predicate, ownership is never surrendered, so the spec sits outside the rewrite's reach by construction. But the critique's correction is adopted: the mapping is an _analogy_, not an exact implementation. Everitt's theorem concerns value functions that anticipate the consequences of modification and evaluate resulting trajectories under the current utility; a license check is a static behavior-preservation proof — a stronger, narrower conservativeness condition with no trajectory evaluation at all. The guarantee that transfers is goal-content protection of the spec, not the theorem's full anticipatory optimality claim. Philosophically, this is the pragmatist license (self-corrective inquiry needs no foundation \[14\]) plus Awodey's schematism (each stage needs only the previous stage's hypotheses \[12\]) — with the checker kept outside the loop because neither substitutes for it.

= Build this first: the opt_q2 slice

A corpus-MDL-modulo-licensed-relations library learner, external and certificate-producing, extending the opt_q1 pattern with zero kernel changes — amended per the critique.

+ *Declare the new-name pathway (design prerequisite, was missing).* Specify how a discovered abstraction enters the library: a generated spec-module addition stating the synthesized relation-object contract and taking guard ownership of the new name, subject to human review, plus a corpus-refactoring transaction plan for rewriting call sites (initially: report proposed rewrites; do not auto-apply to spec or test faces). Until this lands, novel-abstraction MDL gains are computed and reported as hypothetical.
+ *Freeze and version the relevance variable.* Declare the current corpus — the test pins, the README literate blocks, the library files themselves — as *spec-corpus v1*, a first-class artifact with a diversity audit noting its skew toward soundness pins. Per Baxter and Tripuraneni \[72, 73\], this document is the definition of library quality; it must be reviewable.
+ *Build the two-sorted, relation-keyed e-graph* as an external tool on `rust-ic-net`: merges require relation witnesses from the licensed vocabulary (`nat.opt`, `case.opt`, opt_q1 map fusion — the only schematic seed); congruence closure gated by discharged `respects` obligations, never by Pi-typechecking; code-as-data positions admit only `tree_eq`.
+ *Design the schematic-rule license.* The genuinely new licensing object: a quantified rewrite-rule family (`rel_pi`/`pointwise`-shaped) applicable at any matching site, with its own guard policy and load-time re-verification. Without it, axis (a) is near-syntactic MDL and should be labeled as such.
+ *Run babble-style anti-unification over e-classes* to propose candidates; apply the *realizability gate* — synthesize each candidate's relation contract, attempt the license proof via the coverage template, discard on failure, and instrument the discard rate (if it dominates, invert the pipeline Hetzl-style: search only within witness-reachable space).
+ *Emit and rank.* Survivors that rebind incumbents ship as `(e', cert)` overlays into an experimental barrel (`prelude.opt2.disp`); genuinely new abstractions route through step 1. Rank on the two-axis frontier — corpus MDL delta (modulo the licensed vocabulary) versus measured steps over spec-corpus v1, re-measured on multiple eager backends — with barrel-level (whole-suite, whole-corpus) comparison before any promotion, and hysteresis: candidates earn tenure across corpus versions, ACT-R style \[71\].

Attachment points all exist: the licensing guards and coverage templates (write interface), driver-stamped certs and splice reconciliation (deployment), `behavioral_specs` (where synthesized contracts land), the differential five-backend harness (free correctness oracle), and the `rust-ic-net` trace machinery (cost provenance). *Success criterion:* one abstraction not present in the hand-written library, discovered by anti-unification, whose synthesized contract's license proof discharges automatically, and which lands measurably on the frontier — with the deployment half explicitly allowed to be a reviewed proposal rather than an automatic commit. That single artifact validates the layered objective, and — pending the adjacent-literature survey Section 7 mandates — is the reflective-e-graph result worth writing up.

Failure modes to instrument from day one: metric thrash under corpus edits (smoothed objectives, hysteresis); corpus overfit (version and grow the corpus before trusting any global refactor); Goodhart on steps (backend-declared units, never a scalar target); realizability-gate waste (instrument the discard rate); congruence leaks (defense in depth via load-time re-licensing and mandatory differential pins); jointly-bad overlay sets (barrel-level evaluation); optimization pressure drifting into the trusted layer (freeze, human review); legibility divergence (the spec face stays the human artifact; if optimized faces become de-facto reading material, a human-in-the-loop review norm is the only known fix); and checking-path stagnation misread as failure (expected by design).

= Open problems

Honest statement of what nobody knows, disp included:

+ *No computable, stable measure of abstraction quality exists.* The true objective (minimal sufficient statistic, sophistication) is incomputable \[16, 20\] and unstable under logarithmic slack changes \[21\]. Every practical metric is an uncertifiable approximation; monotone certified improvement is the ceiling.
+ *The Bad Company problem is unsolved* \[5\]: no necessary-and-sufficient criterion separates good abstraction principles from disastrous ones, and goodness is provably non-local. Joint criteria (consistency, conservativeness) are necessary, not known sufficient.
+ *Equality saturation over a reflective calculus* has no audited published treatment — but the negative claim rests on this project's searches; slotted/binder-aware e-graphs, egglog conditional congruence, and context-sensitive variants must be surveyed before the gap is asserted in print.
+ *Schematic rewrite licensing* — quantified rule families with guard-policed load-time re-verification — is a new licensing object disp needs and nobody has designed; without it, library learning modulo the licensed theory degenerates to near-syntactic compression.
+ *The realizability gap* \[27, 28\]: which corpus-level compressions admit typed, licensable abstractions is unresolved beyond restricted cut shapes; whether reflection enlarges the realizable class is completely open.
+ *Does compression shorten proofs?* The bootstrapping argument's load-bearing conjecture. DreamCoder shows compression aids search empirically \[50\]; the proof-length version is unestablished, and no acceleration theorem for self-improvement exists anywhere \[53\].
+ *No $epsilon$-sound rewriting exists for programs.* The RL literature has bisimulation metrics and bounded-regret abstraction \[67, 68\]; program optimization has only exact e-classes. "$epsilon$-interchangeable for this loss, with certified regret" is buildable on runnable predicates and built nowhere.
+ *What replaces parametricity in an intensional language* \[38\]: whether a checkable is-parametric predicate carves out a fragment large enough for a practical stdlib is unknown — disp's FOUNDATIONS question Q1, and the field's.
+ *Decidability-aware library optimization*: the right abstractions can move questions across the decidable/undecidable boundary \[35\]; keeping user predicates in cheaply-checkable fragments may matter more than size, and no existing objective captures it.
+ *Choosing the ambient category / abstract domain / LoA*: universal properties, Galois connections, and levels of abstraction each define optimality relative to a prior choice \[8, 32, 42\] and none ranks the choices. Whether "choice of category" can itself be made an optimizable, verified object is open.
+ *Resource-sensitive abstraction has no philosophy or mathematics*: every account surveyed is isomorphism-invariant; cost is not. disp would be building this theory, not applying it.
+ *Legibility has no formalization* \[44, 52\]: mathlib optimizes it socially; compression can diverge from it arbitrarily; no objective captures it.
+ *The abstraction/idealization boundary inside specs* \[6\]: no criterion says when a predicate's silence is sound omission versus a false implicit assertion — critical for a system whose specs are its only anchor.
+ *Curriculum–library co-evolution*: auto-curricula plus skill libraries compound empirically \[55\] with no theory of how the spec-generating distribution should evolve so the library keeps transferring.

The shape of the whole answer, compressed one final time: an abstraction is an equivalence with a licensed representative; the only purpose-free goodness criterion is a universal property, and it is partial and relative; the payoff scale is non-elementary; the sound mechanism is a gate-then-frontier over licensed relations; the machinery disp already owns covers the rebinding half, and the three named gaps — new-name introduction, respects-gated congruence, schematic licenses — are the actual work. The bootstrap is philosophically licensed, empirically supported, theoretically unguaranteed, and safe exactly as long as the checker stays outside the loop.

#heading(numbering: none)[References]

Entries verified during the literature audit retain their URLs. Entries not verified are explicitly marked. Partial verifications state exactly what was and was not confirmed.

+ SEP, "John Locke" (2022; entry byline unverified — attribution from model memory). https://plato.stanford.edu/entries/locke/
+ SEP, "George Berkeley" (2021; byline unverified). https://plato.stanford.edu/entries/berkeley/
+ SEP, "Abstract Objects" (2025; byline unverified). https://plato.stanford.edu/entries/abstract-objects/
+ SEP, "Frege's Theorem and Foundations for Arithmetic" (2023). https://plato.stanford.edu/entries/frege-theorem/
+ SEP, "Logicism and Neologicism" (2023). Verified; the detailed demarcation-criteria survey attributed to this entry is likely over-attribution — the pairwise-inconsistency and criteria material is better anchored in \[4\] and the primary Bad Company literature. https://plato.stanford.edu/entries/logicism/
+ P. Godfrey-Smith, "Abstractions, Idealizations, and Evolutionary Biology" (2009). Verified against the full PDF. https://petergodfreysmith.com/PGSAbstractnIdealizn06.pdf
+ N. Cartwright, _How the Laws of Physics Lie_ (1983). Title, author, and role verified via the SEP "Models in Science" entry; internal argument details are from model memory. https://plato.stanford.edu/entries/models-science/
+ L. Floridi, "The Method of Levels of Abstraction", _Minds and Machines_ (2008). https://link.springer.com/article/10.1007/s11023-008-9113-7
+ S. Mac Lane, _Categories for the Working Mathematician_, 2nd ed., Springer GTM 5, section X.7 "All Concepts Are Kan Extensions" (1971/1998). Verified via nLab and Wikipedia cross-check.
+ Wikipedia, "Kan extension" — source of the verified Mac Lane slogan quotation. https://en.wikipedia.org/wiki/Kan_extension
+ SEP, "Category Theory" (2023; byline unverified). https://plato.stanford.edu/entries/category-theory/
+ S. Awodey, "An answer to Hellman's question: 'Does category theory provide a framework for mathematical structuralism?'", _Philosophia Mathematica_ 12(1) (2004). Read from the CMU preprint. https://www.andrew.cmu.edu/user/awodey/preprints/awodeyVhellman.pdf
+ SEP, "Structuralism in the Philosophy of Mathematics" (2023; byline unverified). https://plato.stanford.edu/entries/structuralism-mathematics/
+ C. Legg and C. Hookway, "Pragmatism", SEP (2024). https://plato.stanford.edu/entries/pragmatism/
+ J.-P. Marquis, _From a Geometrical Point of View_ (Springer, 2009). Bibliographic existence verified via nLab; the Erlangen-program thesis attributed to it is (unverified — from model memory).
+ N. Vereshchagin and P. Vitányi, "Kolmogorov's Structure Functions and Model Selection" (2004). https://arxiv.org/abs/cs/0204037
+ P. Gács, J. Tromp, and P. Vitányi, "Algorithmic Statistics" (2001). arXiv math/0006233, verified via the arXiv export API.
+ P. Grünwald, "A tutorial introduction to the minimum description length principle" (2004). https://arxiv.org/abs/math/0406077
+ J. Rissanen, "Modeling by shortest data description", _Automatica_ (1978). (unverified — from model memory)
+ P. Vitányi, "Meaningful Information" (2006). https://arxiv.org/abs/cs/0111053
+ L. Antunes and L. Fortnow, "Sophistication Revisited", _Theory of Computing Systems_ (2009). Verified via the dblp API; DOI 10.1007/s00224-007-9095-5.
+ C. H. Bennett, "Logical Depth and Physical Complexity", in _The Universal Turing Machine: A Half-Century Survey_ (1988). Title, venue, year, and definition verified via the Wikipedia "Logical depth" article; the slow-growth law and shallow-status details are (unverified — from model memory).
+ N. Ay, M. Müller, and A. Szkoła, "Effective Complexity and its Relation to Logical Depth" (2010). https://arxiv.org/abs/0810.5663
+ G. Boolos, "Don't Eliminate Cut", _Journal of Philosophical Logic_ (1984). Verified via the dblp API; DOI 10.1007/BF00247711.
+ V. P. Orevkov, "Lower bounds for increasing complexity of derivations after cut elimination", _Zapiski Nauchnykh Seminarov LOMI_ 88 (1979). Verified via the reference list and introduction of \[27\].
+ R. Statman, "Lower bounds on Herbrand's theorem", _Proc. AMS_ 75 (1979). Verified via the reference list and introduction of \[27\].
+ S. Hetzl, A. Leitsch, G. Reis, and D. Weller, "Algorithmic Introduction of Quantified Cuts", _Theoretical Computer Science_ 549 (2014). https://arxiv.org/abs/1401.4330
+ G. Ebner, S. Hetzl, A. Leitsch, G. Reis, and D. Weller, "On the Generation of Quantified Lemmas", _Journal of Automated Reasoning_ 63(1) (2019). Verified via Hetzl's TU Wien research page. https://www.dmg.tuwien.ac.at/hetzl/research/index.html
+ S. Eberhard and S. Hetzl, "On the compressibility of finite languages and formal proofs", _Information and Computation_ 259 (2018). Verified via Hetzl's TU Wien research page. https://www.dmg.tuwien.ac.at/hetzl/research/index.html
+ M. Grohe and N. Schweikardt, "The succinctness of first-order logic on linear orders" (2005). arXiv cs/0502047, verified via the arXiv export API. Corrected reading applied in Section 3.4: FO2 and FO3 polynomially equi-succinct; FO4 exponentially more succinct than FO3; the non-elementary gap is MSO's FO-expressive fragment versus FO.
+ L. Hella and M. Vilander, "The Succinctness of First-order Logic over Modal Logic via a Formula Size Game" (2016). https://arxiv.org/abs/1604.07225
+ nLab, "Kan extension" — technical formulation (adjoint to precomposition, pointwise (co)end formulas). https://ncatlab.org/nlab/show/Kan+extension
+ D. Shiebler, "Kan Extensions in Data Science and Machine Learning" (2022). https://arxiv.org/abs/2203.09018
+ P. Mehta and D. J. Schwab, "An exact mapping between the Variational Renormalization Group and Deep Learning" (2014). https://arxiv.org/abs/1410.3831
+ N. Israeli and N. Goldenfeld, "Coarse-graining of cellular automata, emergence, and the predictability of complex systems" (2006). https://arxiv.org/abs/nlin/0508033
+ N. Tishby, F. C. Pereira, and W. Bialek, "The information bottleneck method" (2000). https://arxiv.org/abs/physics/0004057
+ C. E. Shannon, "Coding theorems for a discrete source with a fidelity criterion" (1959). (unverified — from model memory)
+ J. C. Reynolds, "Types, Abstraction and Parametric Polymorphism", _Information Processing 83_ (1983). Title, venue, and content verified via secondary sources; the scanned PDF has no extractable text layer, so the exact thesis wording is quoted here in its canonical form ("enforcing"). https://people.mpi-sws.org/~dreyer/tor/papers/reynolds.pdf
+ P. Wadler, "Theorems for Free!", _FPCA_ (1989). Verified via Wadler's topic page. https://homepages.inf.ed.ac.uk/wadler/topics/parametricity.html
+ B. Liskov and S. Zilles, "Programming with Abstract Data Types", _SIGPLAN Symp. on Very High Level Languages_ (1974). Verified via dblp; DOI 10.1145/800233.807045. https://dblp.org/search?q=Programming+with+abstract+data+types+Liskov
+ P. Cousot and R. Cousot, "Abstract interpretation: a unified lattice model...", _POPL_ (1977). https://www.di.ens.fr/~cousot/COUSOTpapers/POPL77.shtml
+ P. Cousot and R. Cousot, "Systematic Design of Program Analysis Frameworks", _POPL_ (1979). https://www.di.ens.fr/~cousot/COUSOTpapers/POPL79.shtml
+ M. Felleisen, "On the Expressive Power of Programming Languages", _Science of Computer Programming_ 17 (1991). Verified via dblp; DOI 10.1016/0167-6423(91)90036-W. https://dblp.org/search?q=On+the+expressive+power+of+programming+languages+Felleisen
+ H. Massalin, "Superoptimizer: A Look at the Smallest Program", _ASPLOS_ (1987). Verified via dblp; DOI 10.1145/36206.36194. https://dblp.org/search?q=Superoptimizer+Massalin
+ E. Schkufza, R. Sharma, and A. Aiken, "Stochastic Superoptimization", _ASPLOS_ (2013). https://arxiv.org/abs/1211.0557
+ W. Taha and T. Sheard, "MetaML and multi-stage programming with explicit annotations", _TCS_ 248 (2000). Verified via dblp; DOI 10.1016/S0304-3975(00)00053-0. https://dblp.org/search?q=MetaML+multi-stage+programming+Taha+Sheard
+ M. Willsey, C. Nandi, Y. R. Wang, O. Flatt, Z. Tatlock, and P. Panchekha, "egg: Fast and Extensible Equality Saturation", _POPL_ (2021). https://arxiv.org/abs/2004.03082
+ Y. Zhang, Y. R. Wang, O. Flatt, D. Cao, P. Zucker, E. Rosenthal, Z. Tatlock, and M. Willsey, "Better Together: Unifying Datalog and Equality Saturation", _PLDI_ (2023). https://arxiv.org/abs/2304.04332
+ D. Cao, R. Kunkel, C. Nandi, M. Willsey, Z. Tatlock, and N. Polikarpova, "babble: Learning Better Abstractions with E-Graphs and Anti-Unification", _POPL_ (2023). Algorithm verified at PDF level. https://arxiv.org/abs/2212.04596
+ K. Ellis et al., "DreamCoder: Growing generalizable, interpretable knowledge with wake-sleep Bayesian program learning" (2020). https://arxiv.org/abs/2006.08381
+ M. Bowers, T. X. Olausson, L. Wong, G. Grand, J. B. Tenenbaum, K. Ellis, and A. Solar-Lezama, "Top-Down Synthesis for Library Learning" (Stitch), _POPL_ (2023). https://arxiv.org/abs/2211.16605
+ The mathlib Community, "The Lean Mathematical Library", _CPP_ (2020). https://arxiv.org/abs/1910.09336
+ J. Schmidhuber, "Gödel Machines: Self-Referential Universal Problem Solvers Making Provably Optimal Self-Improvements" (2003). https://arxiv.org/abs/cs/0309048
+ B. Jay, Tree Calculus (companion site to _Reflective Programs in Tree Calculus_). Reflective claims verified. https://treecalcul.us/
+ G. Wang et al., "Voyager: An Open-Ended Embodied Agent with Large Language Models" (2023). https://arxiv.org/abs/2305.16291
+ R. Shwartz-Ziv and N. Tishby, "Opening the Black Box of Deep Neural Networks via Information" (2017). https://arxiv.org/abs/1703.00810
+ A. M. Saxe et al., "On the information bottleneck theory of deep learning", _ICLR_ / _J. Stat. Mech._ (2018/2019). https://doi.org/10.1088/1742-5468/ab3985
+ G. Alain and Y. Bengio, "Understanding intermediate layers using linear classifier probes" (2016). https://arxiv.org/abs/1610.01644
+ F. Locatello et al., "Challenging Common Assumptions in the Unsupervised Learning of Disentangled Representations" (2019). https://arxiv.org/abs/1811.12359
+ I. Higgins et al., "Towards a Definition of Disentangled Representations" (2018). https://arxiv.org/abs/1812.02230
+ A. Achille and S. Soatto, "Emergence of Invariance and Disentanglement in Deep Representations" (2017). https://arxiv.org/abs/1706.01350
+ J. Wentworth, "Testing The Natural Abstraction Hypothesis: Project Intro" (2021). https://www.lesswrong.com/posts/cy3BhHrGinZCp3LXE/testing-the-natural-abstraction-hypothesis-project-intro
+ J. Wentworth, "The Telephone Theorem" (2021). https://www.greaterwrong.com/posts/jJf4FrfiQdDGg7uco/the-telephone-theorem-information-at-a-distance-is-mediated
+ L. Chan, L. Lang, and E. Jenner, "Natural Abstractions: Key Claims, Theorems, and Critiques" (2023). https://www.greaterwrong.com/posts/gvzW46Z3BsaZsLc25/natural-abstractions-key-claims-theorems-and-critiques-1
+ L. Li, T. J. Walsh, and M. L. Littman, "Towards a Unified Theory of State Abstraction for MDPs", _ISAIM_ (2006). Verified via dblp. https://dblp.org/search?q=Towards+a+Unified+Theory+of+State+Abstraction
+ B. Ravindran and A. G. Barto, "SMDP Homomorphisms: An Algebraic Approach to Abstraction in Semi-Markov Decision Processes", _IJCAI_ (2003). Verified via dblp. https://dblp.org/search?q=SMDP+Homomorphisms+Ravindran
+ N. Ferns, P. Panangaden, and D. Precup, "Metrics for Finite Markov Decision Processes", _UAI_ (2004). https://arxiv.org/abs/1207.4114
+ D. Abel, D. E. Hershkowitz, and M. L. Littman, "Near Optimal Behavior via Approximate State Abstraction" (2016). https://arxiv.org/abs/1701.04113
+ W. G. Chase and H. A. Simon, "Perception in Chess", _Cognitive Psychology_ 4(1) (1973). Venue and identity verified via DOI record; technical summary from model knowledge of the paper. https://doi.org/10.1016/0010-0285(73)90004-2
+ R. E. Korf, "Macro-Operators: A Weak Method for Learning", _Artificial Intelligence_ 26(1) (1985). Venue and identity verified via DOI record; technical summary from model knowledge of the paper. https://doi.org/10.1016/0004-3702(85)90012-8
+ J. R. Anderson et al., "An integrated theory of the mind" (ACT-R), _Psychological Review_ 111(4) (2004). https://doi.org/10.1037/0033-295X.111.4.1036
+ J. Baxter, "A Model of Inductive Bias Learning", _JAIR_ 12 (2000). https://arxiv.org/abs/1106.0245
+ N. Tripuraneni, C. Jin, and M. I. Jordan, "Provable Meta-Learning of Linear Representations" (2020). https://arxiv.org/abs/2002.11684
+ T. Everitt, D. Filan, M. Daswani, and M. Hutter, "Self-Modification of Policy and Utility Function in Rational Agents" (2016). https://arxiv.org/abs/1605.03142
