// Bundle the disp compiler into ../player/compiler.js: one script that opens straight from disk,
// holding a worker (started from a Blob URL) with the elaborator, the rust-eager evaluator as
// WebAssembly and the scope's sources (compiler.ts SCOPE) in a virtual filesystem. The player
// loads it the first time something needs compiling. Run from anywhere:
//   npx tsx evaluators/rust-ic-strands/programs/bundle.ts
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { build, type Plugin } from "esbuild"
import { SCOPE } from "./compiler.js"

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, "../../..")
const files = Object.fromEntries(SCOPE.map(f => ["/" + f, readFileSync(join(repo, f), "utf-8")]))

/// node:fs reads the scope's sources, node:path is the website's posix shim.
const shims: Plugin = {
  name: "strands-shims",
  setup(b) {
    b.onResolve({ filter: /^node:fs$/ }, () => ({ path: "fs", namespace: "vfs" }))
    b.onLoad({ filter: /.*/, namespace: "vfs" }, () => ({
      loader: "js",
      contents: `const files = ${JSON.stringify(files)};
export function existsSync(p) { return Object.hasOwn(files, p); }
export function readFileSync(p) { if (existsSync(p)) return files[p]; throw new Error("ENOENT: " + p + " is not in the player's compiler"); }
export default { existsSync, readFileSync };`,
    }))
    b.onResolve({ filter: /^node:path$/ }, () => ({ path: join(repo, "website/src/lib/disp/shims/path.ts") }))
  },
}

const out = await build({
  entryPoints: [join(here, "compiler-worker.ts")], bundle: true, write: false, format: "iife", target: "es2022",
  minify: true, legalComments: "none", plugins: [shims],
  define: { RUST_EAGER_WASM: JSON.stringify(readFileSync(join(repo, "website/static/rust_eager.wasm")).toString("base64")) },
  // The repo's own compiler settings (the website's tsconfig extends a file only SvelteKit generates).
  tsconfigRaw: { compilerOptions: { target: "ES2022", strict: true } },
  // The elaborator reads its working directory and settings off node's process.
  banner: { js: `var process = { env: {}, cwd: () => "/", argv: [] };` },
})
const worker = out.outputFiles[0].text

const page = `// generated by programs/bundle.ts from programs/compiler-worker.ts; do not edit
// The disp compiler for the player (index.html loads it on first use), in a worker:
//   StrandsDisp.ready       resolves once the prelude, lib/list.disp and programs.disp have loaded
//   StrandsDisp.compile(s)  resolves to { term, head, kind } (compiler.ts Compiled), or rejects
//   StrandsDisp.names       every top-level definition in scope as { name, tree }, tree in ternary
(() => {
  const worker = new Worker(URL.createObjectURL(new Blob([${JSON.stringify(worker)}], { type: "text/javascript" })));
  const waiting = new Map();
  let next = 0;
  const D = window.StrandsDisp = { names: [] };
  D.ready = new Promise((ok, no) => {
    worker.onerror = e => no(new Error(e.message || "the compiler's worker failed"));
    worker.onmessage = ({ data: m }) => {
      if (m.ready) { D.names = m.names; D.ms = m.ms; ok(D); }
      else if (m.fatal) no(new Error(m.fatal));
      else { const [ok, no] = waiting.get(m.id); waiting.delete(m.id); m.error === undefined ? ok(m.result) : no(new Error(m.error)); }
    };
  });
  D.compile = src => D.ready.then(() => new Promise((ok, no) => { const id = next++; waiting.set(id, [ok, no]); worker.postMessage({ id, src }); }));
})();
`
writeFileSync(join(here, "../player/compiler.js"), page)
console.log(`player/compiler.js: ${page.length} bytes (worker ${worker.length})`)
