#!/usr/bin/env bash
# Compile the strand lattice to WebAssembly and embed it in player/engine.js, so
# player/index.html opens straight from disk and runs the engine the tests check.
set -euo pipefail
self="$(readlink -f "$0")"
cd "$(dirname "$self")/crate"
if ! command -v wasm-ld >/dev/null; then
  exec nix shell nixpkgs#lld -c "$self" "$@"
fi
export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_LINKER=wasm-ld
cargo rustc --lib --profile wasm --target wasm32-unknown-unknown --crate-type cdylib -q
wasm=target/wasm32-unknown-unknown/wasm/rust_ic_strands.wasm
{
  printf '// generated by build-player.sh from the rust-ic-strands crate; do not edit\n'
  printf 'window.STRANDS_WASM = "'
  base64 -w0 "$wasm"
  printf '";\n'
} > ../player/engine.js
echo "player/engine.js: $(stat -c %s "$wasm") bytes of wasm"
# The disp programs the player offers, compiled with the real elaborator.
(cd ../../.. && npx tsx evaluators/rust-ic-strands/programs/emit.ts)
