[package]
name = "test6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disp = { version = "0.1.0", path = "../.." }
emulator_6502 = "1.1.0"
hex-literal = "0.3.4"
