#!/usr/bin/env bash
# Compile the engine to WebAssembly and embed it in player/engine.js, so player/index.html
# opens straight from disk (no server) and runs the very engine the tests check.
set -euo pipefail
self="$(readlink -f "$0")"
cd "$(dirname "$self")/crate"
# The wasm target needs a wasm linker; on NixOS borrow one for the duration of the build.
if ! command -v wasm-ld >/dev/null; then
  exec nix shell nixpkgs#lld -c "$self" "$@"
fi
export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_LINKER=wasm-ld
cargo rustc --lib --profile wasm --target wasm32-unknown-unknown --crate-type cdylib --features player -q
wasm=target/wasm32-unknown-unknown/wasm/rust_ic_mesh.wasm
{
  printf '// generated by build-player.sh from the rust-ic-mesh crate; do not edit\n'
  printf 'window.MESH_WASM = "'
  base64 -w0 "$wasm"
  printf '";\n'
} > ../player/engine.js
echo "player/engine.js: $(stat -c %s "$wasm") bytes of wasm"
